package(default_visibility = ["//visibility:public"])

cc_library(
    name = "simple-generator",
    srcs = ["simple-generator.cc"],
    hdrs = ["simple-generator.h"],
    deps = ["//bubbles-motion-planning/src:random-point-generator-interface"],
)
